# test01
# Alpha particle emissions in the 12C exited states (E_lab = 2.87)
/run/initialize

###################################

# Alpha_0
/gps/source/intensity 10
/gps/particle alpha
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 40 deg
/gps/ang/minphi 130 deg
/gps/ang/maxphi 200 deg
#/gps/direction 1 0 0
/gps/energy 13.79 MeV

###################################

# Alpha_1

/gps/source/add 2
/gps/particle alpha
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
#/gps/direction 1 0 0
/gps/energy 10.21 MeV

###################################

# Alpha_2

/gps/source/add 2
/gps/particle alpha
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
#/gps/direction 1 0 0
/gps/energy 7.58 MeV

###################################

# Alpha_3

/gps/source/add 2
/gps/particle alpha
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
#/gps/direction 1 0 0
/gps/energy 5.94 MeV

###################################

# Alpha_4

/gps/source/add 2
/gps/particle alpha
/gps/pos/type Point
/gps/pos/centre 0. 0. 0. cm
/gps/ang/type iso
#/gps/direction 1 0 0
/gps/energy 5.38 MeV

###################################


/run/beamOn 1
